### ISSUE TITLE
Add something like Foldable1 / Traverse1 ?

### ISSUE THREAD

**Issue by refried** [non/cats#145]
These are nice.

**Comment by non** [comment]
I think instead of `Foldable1` we should call it `Reducible` to parallel the relationship between `foldLeft` and `reduceLeft`.

**Comment by ceedubs** [comment]
I definitely would like to see these type classes.

I do like that Reducible would draw a parallel between foldLeft and reduceLeft. However, in the grand scheme of things, I'm wondering if Foldable1 would be more consistent/clear. Assuming we would have Traverse1/Traverse, the relationship between Foldable1/Foldable might be more clear. We have already chosen to use MonoidK and SemigroupK instead of the scalaz names to express their relationships with Monoid/Semigroup (respectively).

Also people hopefully have a fear of std lib's reduceLeft since it blows up on empty collections ;)

**Comment by non** [comment]
Fixed in #298.
