### ISSUE TITLE
Publish ScalaDocs

### ISSUE THREAD

**Issue by ceedubs** [non/cats#156]
It would be nice to have a consistently up-to-date ScalaDoc published somewhere for Cats. Is this something we can automate through Travis CI?

**Comment by travisbrown** [comment]
It looks like @stew already set up sbt-site to include [the API docs](http://non.github.io/cats/api/), so they're published with the rest of the site, and are just as up-to-date.

**Comment by ceedubs** [comment]
Oh wow that's great :D

Are we linking to those anywhere? Maybe we can hijack this issue and turn it into one for a well-placed link to the API docs.

**Comment by travisbrown** [comment]
If the project is going to move to typelevel someday, it might be best to wait before sharing the link very widely, since having people land on stale API docs for the rest of time is kind of annoying. Otherwise I'm all for sharing the link—I've just done the machine-readable version of that in #158.
