### ISSUE TITLE
Transformers for stdlib data types

### ISSUE THREAD

**Issue by adelbertc** [non/cats#234]
`ListT` and `OptionT` come to mind, I've found those to be useful from time to time. `Kleisli` as well.

Semi-related to https://github.com/non/cats/issues/229

**Comment by ceedubs** [comment]
`Kleisli` is already there: https://github.com/non/cats/blob/master/data/src/main/scala/cats/data/Kleisli.scala

Agreed on the others.

**Comment by rossabaker** [comment]
Quoth the README:
> std: Standard type class instances and other useful data types.

I'd say `ListT` and `OptionT` belong in std, and now wonder why not also `Kleisli` and `Cokleisli`?  Or, if these all get dumped into data, then maybe std should be redefined as simply "Standard type class instances."

**Comment by mandubian** [comment]
`EitherT` is quite useful too even if you often need to help a bit the compiler by specifying the types

**Comment by non** [comment]
We have `XorT` already, and we have a PR for `OptionT` right now (#304).

I don't think there is a plan for `ListT` as of yet.

What should the scope of this issue be?

**Comment by mandubian** [comment]
you could close it and create one for `ListT` alone. `ListT` could be useful in the future

**Comment by ceedubs** [comment]
I'm going to close this out since we have `OptionT` and the scope of this ticket is a bit vague. We can open separate issues for specific transformers if we want them.

`ListT` probably deserves its own GitHub issue, because I anticipate a lot of bikeshedding over it violating the associative law if we go down that route :)
