### ISSUE TITLE
How to encode typeclasses that require Either

### ISSUE THREAD

**Issue by julien-truffaut** [non/cats#24]
`Choice`, `ProChoice` and probably other typeclasses have methods that take or produce `Either`. Ideally, we would use `cats.data.Or` instead of `scala.Either` but it means that `Or` need to be defined in core.

What is your thought?

**Comment by non** [comment]
I'm open to moving `Or` into `core` if we decide to add these types to `core`.

Since we're going for relatively small modules, I think there was an idea to move `Arrow`, `Category`, etc into an `arrows` module. In that case, we could have `arrows` depend on `data`.

**Comment by julien-truffaut** [comment]
if we make `arrows` depend on `data` it means that we can't implement `arrow` typeclasses on data

**Comment by non** [comment]
Right.

Maybe ultimately we'll need to put `Or` in `core` just to sort out this dependency! :)

**Comment by julien-truffaut** [comment]
if we decide to go ahead with `Or` in `core`, in which package shall we put it?

**Comment by julien-truffaut** [comment]
or maybe in package cats.base, what do you think?

**Comment by julien-truffaut** [comment]
I would like to discuss a few options:
*     define in core a typeclass for `Or` like type e.g. `trait OrLike[O[+_, +_]]  {...} ` and use it to encode other typeclass methods requiring an `Either`. For example choice could be encoded like: 
```scala
 trait Choice[P[_, _]] extends Category[P] { self =>
  def choice[O[_, _], A, B, C](f: P[A, C], g: P[B,C])(implicit O: OrLike[O]): P[O[A, B], C]
}
```
*    use `scala.Either` e.g. 
```scala
 trait Choice[P[_, _]] extends Category[P] { self =>
  def choice[A, B, C](f: P[A, C], g: P[B,C]): P[Either[A, B], C]
}
```
*    create a module arrow, move typeclasses like `Arrow`, `Category`, `Profunctor` there. Then update module dependency such as arrow depends on data. So we can implement `Choice` and `Prochoice` using `Or`
*    move `Or` to core

1 is probably over complicated
2 is a pain to use, especially since we defined our own version (`Or`)
3 is a no go because it would mean we can't implement an arrow instance for a data structure
4 breaks the neat separation between typeclasses and data structure.

At the moment, I would tend to lean toward 4 because a proper Sum type is the foundation of a functional programming language. So it makes sense to be in the "core" of cats but I can see that this argument is very thin...  

Do you have other ideas? or other opinions about the options I mentioned

**Comment by ceedubs** [comment]
Some thoughts that I have that should probably be taken with a grain of salt:

Option 1 also sounds a little complicated to me. I'm afraid that for newcomers type signatures would start looking as confusing as those from std lib that have `CanBuildFrom`. As you said, a sum type is pretty fundamental. The main argument I can see for this approach is to avoid making people create extra allocations if they don't want to work in terms of the sum type we end up settling on. That in itself is a pretty reasonable argument. Maybe for convenience we'd want to offer derived alternatives with the sum type fixed to `Either` and/or `Or` in places this is used.

Since a sum type is so fundamental, I don't really have a problem with it going into `core`. We'd probably need to introduce a product type into `core` as well if we didn't already have tuples in Scala. I think that as things progress we will likely realize that the simple `core`/`data` split is a bit naive (though I think it's a good starting place). I think just about everyone who uses cats is going to want to end up using some core type classes, some std instances, and some cats data structures. I think our modularity will need to end up coming from teasing out less used abstractions and structures into their own modules.

**Comment by ceedubs** [comment]
Oops I forgot to leave one of my thought on Option 1. If we go with this approach, I don't think we should force covariance on the type constructor. We can just create `OrLike[_, _]` and leave it up to the implementing structure whether or not it uses variance.

**Comment by milessabin** [comment]
I guess I should point to [the wip/smc branch of shapeless](https://github.com/milessabin/shapeless/blob/wip/smc/core/src/main/scala/shapeless/smc.scala) ... this is a proof of concept for the way I'd like to move things for shapeless 3.0.0. There is a close connection between the structure used there and `Profunctor`/`Choice`.

**Comment by ceedubs** [comment]
We now have `Xor` in the `core` module. I'm going to close out this issue, but I'm happy to reopen it if people want further discussion on whether that's the right long-term home for this.
