### ISSUE TITLE
Kleisli monoid

### ISSUE THREAD

**Issue by NightRa** [non/cats#247]
We should add the Kleisli monoid that comes from kleisli arrows; (Monad m) => Monoid (Kleisli m a a).
The instance in scalaz is the reader variant that requires the codomain to be a monoid.

Personally, I use the kleisli monad composition monoid **a lot**, and I haven't ever used the reader instance.
Opinions regarding what instance to implement?

**Comment by ceedubs** [comment]
Composition does seem more natural for combining arrows than using the `Monoid` of the result type to me. However, the composition approach could only provide a `Semigroup`, not a `Monoid`, couldn't it? I don't think that in the general case you can provide `empty` for `A => M[B]`.

**Comment by travisbrown** [comment]
@ceedubs Because the composition monoid would be available for endomorphic arrows, the `empty` would just be `F.pure(_)`.

I know I've used the "reader" monoid for Kleisli arrows, and I'd prefer to provide the composition monoid via a newtype for endomorphic arrows (this seems arguably more intuitive and definitely more standard than the reverse).

**Comment by ceedubs** [comment]
@travisbrown ah that makes sense. Thanks!

**Comment by edmundnoble** [comment]
I'm working on this right now, almost done. Pull request incoming.

**Comment by edmundnoble** [comment]
Would it be useful to anyone if I introduced a

**Comment by edmundnoble** [comment]
I think this can be closed, now that #478 is merged.

**Comment by non** [comment]
Thanks!
