### ISSUE TITLE
Where should `Free`, `Trampoline`, and `function0Instance` live?

### ISSUE THREAD

**Issue by refried** [non/cats#258]
"Our `data` depends on it!!"

Please discuss.

**Comment by refried** [comment]
Calling `Trampoline#run` requires a `Comonad[Function0]`

**Comment by ceedubs** [comment]
Here are my thoughts:
You pretty much need `Function0` and `Function1` to do functional programming in Scala. I think they should be in `core`. I think instances for things like `Set`, `Vector`, etc should be in a separate module (like `std`), but I don't see much merit in keeping _everything_ from the standard library out of `core`. I think it would just be an uphill battle with no real return.

A discussion about `Free` is happening in #183. It sounds like the current plan is to give it its own module. That sounds fine to me, because it would be needed by `data` and might separately be needed by `std`. I think `Trampoline` belongs where `Free` is.

**Comment by refried** [comment]
Sub-question: Currently I don't see any instances in `std` at all; should they go into the `Comonad` companion, for example?

**Comment by ceedubs** [comment]
I think we should probably follow the pattern used for `std` instances. I think it's going to be a pain if we have instances for a particular type spread among the companion objects for those type classes. We can probably combine `Function0` and `Function1` instances into a `cats.function._` import. Does that sound reasonable?

**Comment by refried** [comment]
In scalaz, I think I only need to import `scalaz.std.list._` when I'm trying to pass an implicit `Foldable[List]` or `Plus[List]`.  And usually I hit the compilation error at least once, and then have to say "oh, right", and add that import.  Here, I need to import the instance for `List` because I'm explicitly using `List` in my code.

If I need to manually import `cats.function._` to be able to use `State` (because we want `State` to be trampolined by default), but not explicitly using Function0 in my code, I think that will be super confusing.  I bet the compiler errors will be completely unhelpful too, and send folks on wild goose chases depending on what different implicits they do have in scope.  For this reason, I think we should look for a way to avoid having to manually import instances for these types, which I agree are pretty much needed to do FP in Scala; let's put them on equal standing with the types in cats core, rather than a lower standing.  

What do you think?

**Comment by refried** [comment]
I could you could further make the argument that `Trampoline` is pretty much needed to do FP in Scala too though!  Hmm.

**Comment by ceedubs** [comment]
When working on `State`, [this](https://github.com/non/cats/blob/471553e81d79ab8aadfb12bfa1454f7305149ef4/state/src/main/scala/cats/state/State.scala#L109-L111) made me feel like the function instances (at least `function0`) should be in core.

Since (so far at least) the decision has been to use std lib's `Option` and `List` in Cats instead of creating our own versions, I am wondering if those instances should be in core too. Modularization is hard...

**Comment by refried** [comment]
I agree; automatically finding instances in a suitable companion object is much more user friendly IMO than manual imports.

**Comment by woparry** [comment]
When working on #107 I found it odd that I didn't have Monoid[Function1[A, A]] in core, but I did have the isomorphic Monoid[Kleisli[Id, A, A]].

**Comment by non** [comment]
I'm finally ready to admit defeat on the modularization effort to keep `std` separate from `core`.

The design came from the Algebra project, where it still makes sense. However, it seems like it is causing a lot of inconvenience at every turn here in Cats. Since it primarily protects against a problem that we haven't had yet (privileging built-in implementations in a way that third-parties won't be able to replicate) let's get rid of it.

I'm going to open an issue to move `cats.std` into the `core` project.

**Comment by non** [comment]
Obviously if someone disagrees with me and wants to defend the split I'm happy to talk about it more. But I think I was the person who pushed modularization the hardest, and I've decided that it seems to be more trouble than it is worth in this case.

**Comment by mpilquist** [comment]
:+1:

**Comment by stew** [comment]
I'm thrilled we tried the experiment. It is a great thing that we have this pristine project that nobody is relying on to launch their missiles with and we can experiment with. I think we can mark it as a win that we did the experiment, learned something, and exited gracefully, so I'm all for combining stuff.

I think that a trampoline is a first class abstraction when trying to present a core library for functional programming in scala, So I'd like to see us either move a basic trampoline into core, free into core, or be okay with using the TailCals from the scala stdlib and see if we can make it work, for instance, for the missing many, some methods on Alternative.

**Comment by ceedubs** [comment]
`std` has been merged into `core`, and it seems to have made these pains go away (at the cost of some modularity perhaps). In the future we may reconsider the decision, but as far as I'm concerned this issue has been resolved. What do you think, @refried?

**Comment by refried** [comment]
:+1:
