### ISSUE TITLE
Reader/ReaderT alias?

### ISSUE THREAD

**Issue by adelbertc** [non/cats#382]
We have `Kleisli` and instances for `Function1`, would it be of interest to have something like:

```scala
type Reader[A, B] = Kleisli[Id, A, B]
type ReaderT[F[_], A, B] = Kleisli[F, A, B]

object Reader {
  def fromFunction[A, B](f: A => B): Reader[A, B]
  /** Other useful methods here? */
}
```

**Comment by ceedubs** [comment]
I think `Reader` makes sense. It may be less confusing to users if we pick one of either `ReaderT` or `Kleisli` instead of having both.

I wonder if it might actually be a good idea to rename `Kleisli` to `ReaderT`. It would make the relationship more apparent. And technically I think our `Kleisli` isn't quite a proper Kleisli category, since we don't require that `F` has a monad.

I'm interested to see what other people think.

**Comment by adelbertc** [comment]
I'm pretty interested in renaming Kleisli to ReaderT, would make it consistent with the other transformer names. Possibly make Kleisli the alias instead?

**Comment by adelbertc** [comment]
Seems a few folks in the Gitter channel are in favor of renaming `Kleisli` to `ReaderT` - I know @travisbrown had reservations about it though regarding `Reader` being a special case of `Kleisli`.

One thing I ran into when I thought about working on this was that we also have `Cokleisli` - if we were to move forward with renaming to `ReaderT` would we then call this `CoReaderT` ?

Naming things is hard :-)

**Comment by travisbrown** [comment]
To recap my argument from Gitter: the problem isn't that `Reader` is a special case of `Kleisli` (they're exactly the same type), it's that "reader" is only one application of the more general concept of kleisli arrows.

One example of a use case that doesn't really look anything like the reader monad: Finagle represents RPC services as `A => Future[B]`, and it's useful to be able to work with these things as kleisli arrows. The `A` in this case isn't an environment—it's just the input to a function.

Renaming `Kleisli` to `ReaderT` would be a lot more confusing to people who came across the type used in contexts like these—when they run off to Google "reader monad" they're going to get a lot of information that doesn't have much of anything to do with what they're seeing.

**Comment by non** [comment]
What if we supported both `ReaderT` and `Reader` via type aliases (and companion-esque objects) but kept `Kleisli` as the primary name?

**Comment by mdedetrich** [comment]
With @non here, isn't a type alias the best way to fix this problem? I think having `Reader` is definitely useful if it helps newcomers understand what is probably the most common use of `Kleisli`.

Generally speaking, I think this is the debate of the whole "being completely and mathematically correct in terminology" vs "using terminology which makes it easier for people to pick up" debate. I more lean towards the latter, because if people already understand this terminology, its a lot easier for them to get that a `Reader` is actually a `Kleisli`, its not the same case the other way around.

As an example, with a person still trying to pick up `Cats`, there is a big difference between seeing `Reader` in code (which at least provides context as to what is happening) vs `Kleisli`.

**Comment by travisbrown** [comment]
I'm all for a type alias ([on the record](http://stackoverflow.com/a/29237252/334519)), but just to clarify: my objection to a rename isn't based on a desire for mathematical correctness—it's based on a desire not to have to say "it's called `ReaderT` but we're not really using it as the reader monad here" over and over.

**Comment by ceedubs** [comment]
I guess I always thought of `Reader` as "read"ing an input in a pretty general sense. But looking through some reader monad docs, they do tend to emphasize the "environment" being the item that is read.

It sounds like everyone would be okay with having `Reader/ReaderT` be aliases for `Kleisli`. Since I had previously discouraged this approach, I thought I would weigh in saying that I support this. I say we go for it!
