### ISSUE TITLE
Give up on some of the modularity

### ISSUE THREAD

**Issue by stew** [non/cats#406]
I feel like there is a bunch of tension that perhaps be resolved if we give up on the notion of trying to keep  things modular by having separate {core, std, data (oops), free} artifacts, and just start putting everything in core. We seem to be very often saying, "... if we had a trampoline available in core..." or something. Should we say "Wow, I'm glad we had the opportunity to learn from that failed experiment" and chalk it up to a win?

I'd be thrilled to get a lot of input, even if just :+1: or :-1: from random not-otherwise-contributing peeps out there on this one...

**Comment by milessabin** [comment]
The thing that I've found most jarring is not being precisely clear where the Algebra/Cats line falls. On several occasions now I've thought "What instances to we have for X", gone to Cats and wasted time hunting around before realizing that, "Oh, they're in Algebra". I think this is potentially quite a serious discoverablity problem.

If we can find a solution to that problem, then I think we will also have a solution to the problem for modules within Cats itself.

**Comment by stew** [comment]
To me this is not about "where should B live" bit is about "we thought project B was strictly downstream of project A, but we keep wanting to use stuff from B inside A"

**Comment by non** [comment]
@milessabin It's possible that I've confused that issue by papering over the distinction with type aliases. I imagine if you had to import `algebra.X` instead of `cats.X` that would help prevent that confusion (and instead would create a different kind of annoyance).

**Comment by non** [comment]
@stew So, I don't agree that modularity is a failed experiment. I think there are (at least) three things going on:

1. Some of the modules I/we have created don't make sense. For example, `std` was a bad idea and should be folded into `core` (to be more specific, I think all modules in Cats should have `syntax` and `std` packages). I think that at least 90% of the current annoyance has been around `std` instances not being available in `core`, which I agree has been a problem.

2. Some people are used to having everything in one place, so it's inherently going to be a bit annoying to adjust to any modularity whatsoever.

3. Other people are really excited by modularity and want to push it even harder. See for example the ScalaJS folks, @woparry, and others.

I think if we give up on modularity entirely we cater to group (2) at the expense of group (3). I would prefer to try tackling (1) and seeing where things stand after that.

In general, I think any project "foo" that is primarily around type classes will probably want to provide the packages `foo`, `foo.std` (instances for types that the package depends on), and `foo.syntax` (syntax implicits that use foo's type classes/types). `core` should support this layout and doesn't due to confusion on my part.

**Comment by ceedubs** [comment]
I agree with pretty much everything that has been said in this thread so far. I especially agree with @non's points, and I think that folding `std` into `core` (speaking in terms of modules; the package distinction I think I like) would eliminate 90% of my frustrations I've experienced with this.

**Comment by tpolecat** [comment]
Random peep here.

So, it's really hard to get module boundaries right. I'm pretty sure I have never gotten in right, it just sort of converges to an acceptable ratio of isolation to irritation. So and I think @non's proposal is sensible. Take the most obvious bite and see how it looks.

I personally don't care about jarfile size, so my setpoint is in a different place than the scala-js folks. I guess I'm hoping that a natural balance will emerge and we'll all be equally unhappy and call it good.

**Comment by InTheNow** [comment]
Speaking as a peep from the peanut gallery, that has just helped pull [these modules together](https://github.com/propensive/rapture), sorting out @non 's 1) first makes absolute sense

**Comment by propensive** [comment]
So, I put a lot of effort into modularizing Rapture a couple of years ago (and it's still sort of ongoing) into about 20 modules, and I'd say that certain aspects of the process have been successful, while others have not. The mistakes, I think, were trying to evolve the modules independently, with different repositories and different version numbers; and consequently no clarity over source compatibility between them, let alone binary compatibility. So, with @InTheNow's help, I've just merged them all into the same repository, but publishing to different JARs.

But, I think the modularization, along with a goal of minimizing dependencies between projects, has been quite successful. The additional constraints imposed by modularization do generally result in additional thinking about those module boundaries, but it's a useful thing to spend time thinking about.

One consequence has been that I've frequently ended up with a micro-module containing a single typeclass that links, say, Rapture JSON and Rapture IO: there's a clear lack of justification for either module to depend on the other, but if you only need a subset of the functionality, you can get away with a (potentially) much smaller classpath.

So, although I'm not familiar with the tension with Cats that @stew talks about (also, bear in mind that I'm the only Rapture developer), I'd still give a :+1: to the concept of modularization.

**Comment by rossabaker** [comment]
I previously preferred minimizing jar count over jar size for reasons of `sbt update` performance.  Cached resolution removed this concern.  I've moved to the "modularize unless it hurts" camp, which leaves me agreeing with @non's first step.
