### ISSUE TITLE
Travis CI integration

### ISSUE THREAD

**Issue by ceedubs** [non/cats#45]
I would imagine that we all want this to verify pull requests before they are merged (though please speak up if you have a reason not to go with Travis).

Anyone should be able to submit a PR with a `.travis.yml `. I think @non will probably have to be the one to enable it as described [here](http://docs.travis-ci.com/user/getting-started/).

**Comment by travisbrown** [comment]
One little note: we switched a lot of projects to Travis's container-based infrastructure after [they announced it in December](http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/), and that's been a headache—it seems to have an especially hard time getting snapshot dependencies from Sonatype, for example.

So leaving off `sudo: false` for now is probably a good idea (and may save someone else fifteen minutes of clicking the restart button on tests that are failing because of network errors or for other uninteresting reasons).
