### ISSUE TITLE
Update laws + tests to use EqK as much as possible

### ISSUE THREAD

**Issue by non** [non/cats#515]
Many of our tests were written before `EqK` and so they take a ton of implicit `Eq[_]` parameters. Instead of taking implicit `Eq[F[A]]`, `Eq[F[B]], and `Eq[F[C]]`, we should take implicit `EqK[F]`, `Eq[A]`, `Eq[B]`, and `Eq[C]`.

There are a few reasons to do this. First, we often need both `Eq[A]` and `Eq[F[A]]` anyway. Second, as the number of parameters increases, this keeps things under control. Third, it helps standardize our laws/tests.

**Comment by ceedubs** [comment]
I'm actually not fond of our `EqK` and `ArbitraryK` constraints in tests, and I'm afraid I would propose going in the opposite direction. I think they are more constraining than necessary.

For example, #249 is a PR where I had to relax an `ArbitraryK[F]` constraint to `Arbitrary[F[A]]`. And if it had had an `EqK[F]` constraint, I would have had to relax that too. For purposes of testing, we can create a crude `Eq[Semigroup[A]]` instance if we have an `Arbitrary[A]` by creating a bunch of random `A` values and ensuring that two semigroups give the same output when fed them. However, we cannot create an `EqK[Semigroup]` instance, because that doesn't allow us to add the `Arbitrary` constraint.

I like `EqK` and `ArbK`, and I think they have their use-cases, but I don't think that they should be enforced as constraints when it's just to make code look cleaner and not because a universal instance is actually required.

**Comment by mpilquist** [comment]
I have the same concerns as @ceedubs. In the scodec/cats interop module, I have a `Monad[Decoder]` but I'm not able to meaningfully test the monad laws for that instance due to an `ArbitraryK` requirement in `MonadLaws`.

The best `ArbitraryK[Decoder]` instance I can come up with is consuming an arbitrary number of bits, throwing them away, and returning an arbitrary value:

```scala
implicit val arbKDecoder: ArbitraryK[Decoder] = new ArbitraryK[Decoder] {
  def synthesize[A: Arbitrary]: Arbitrary[Decoder[A]] = {
      val successful = for {
      toConsume <- Gen.chooseNum(0, 32)
      value <- arbitrary[A]
    } yield Decoder(b => Attempt.successful(DecodeResult(value, b.drop(toConsume.toLong))))
    val failure = Gen.const(scodec.codecs.fail(Err("failure")))
    Arbitrary(Gen.frequency(10 -> failure, 90 -> successful))
  }
}
```

**Comment by ceedubs** [comment]
Per a Gitter [discussion](https://gitter.im/non/cats?at=5638cd620d4ff3974d48e045) today, it sounds like we aren't going to go forward with this. I'm going to go ahead and close this out. @non feel free to reopen or comment if you want to continue this discussion.
