### ISSUE TITLE
Foldable.dropWhile_() is not working as advertised

### ISSUE THREAD

**Issue by weihsiu** [non/cats#563]
this is what i get when using Foldable.dropWhile_() in the repl.  the results do not conform with the spec.
```
scala> Foldable[List].dropWhile_(List(2, 4, 5))(_ % 2 == 0)
res46: List[Int] = List(2, 4, 5)

scala> // should return List(5)

scala> Foldable[List].dropWhile_(List(1, 2, 4, 5))(_ % 2 == 0)
res47: List[Int] = List(2, 4, 5)

scala> // should return List(1, 2, 4, 5)
```

**Comment by ceedubs** [comment]
Thanks for spotting this and creating an issue @weihsiu. The fix itself is pretty easy (adding a `!` in the implementation). However when I went to make this fix, I noticed that this probably should have been caught by https://github.com/non/cats/blob/master/tests/src/test/scala/cats/tests/FoldableTests.scala#L32 but this `FoldableCheck` class isn't actually used anywhere. @non do you think those tests should be moved into the `FoldableTests` in the laws module? The `Iterator` requirement is a bit outside of the norm for law tests, but we should certainly add these sort of checks in one way or another. Another option is just using `toList` or `toStreaming` on the `F[A]` instance and checking for consistency instead of requiring an `Iterator`.
