### ISSUE TITLE
Support serial composability in `Validated`

### ISSUE THREAD

**Issue by metasim** [non/cats#604]
Per  [gitter comment](https://gitter.im/non/cats?at=563cbb6fc3b1996c03a247e6), consider some mechanism for composing multiple, serialized `Validated` transformations without having to go back and forth between `Xor` to get `flatMap`.

**Comment by ceedubs** [comment]
To add a little more detail after a follow-up Gitter conversation. It sounds like the consensus is to add a new method to `Validated` that has the same signature as `flatMap` but with a different name, since it will not actually be a monadic `bind` (since it won't be consistent with `ap`).

As is often the case, naming is the hardest part. @metasim suggested `andThen`, which is perhaps a bit overloaded, but I've thought for a while and can't come up with a better name, so I'd be happy with that.
