### ISSUE TITLE
Untested CoflatMap laws

### ISSUE THREAD

**Issue by ceedubs** [non/cats#732]
There are several laws defined in `CoflatMapLaws` that aren't checked in `CoflatMapTests`. It looks like they require some additional `Eq` instances, but other than that I'm not sure whether or not there is a good reason they aren't currently included. Does anyone know?

Paging @fthomas and @non due to git history :)

**Comment by fthomas** [comment]
That is the associativity law of `coflatMap` expressed in terms of `Cokleisli` composition. There is also a law that shows the associativity of `Kleisli` composition in `FlatMapLaws`. I've added them because the associativity is more apparent in this formulation (see also this [Gitter](https://gitter.im/non/cats?at=56683583835961e946e215ff) discussion).

Since those laws are more or less duplicates of existing laws, I'd just test them with a single type so that code coverage do not mark them as unused. If they pass for one type, I guess the other tests and laws guarantee that they also pass for all other types.

I'll try to come up with test for those.
