### ISSUE TITLE
add typeclass instances for scala std Future

### ISSUE THREAD

**Issue by lvicentesanchez** [non/cats#76]
I still have to use scala std Future a lot so... this would be quite useful. I think at least Monad, Comonad and Monoid should be implemented. I volunteer to implement them over the weekend.

**Comment by ceedubs** [comment]
Scalaz implements these by making the instance a `def` that takes an implicit `ExecutionContext`. I don't really like this approach. I think that `implicit` arguments should be reserved for type class instances and not used for "configuration" objects.

I think something like `ExecutionContext => Future[A]` is a better thing to consider a monad (though really even that is probably a little bit dodgy since futures immediately start executing). We could potentially wrap `ExecutionContext => Future[A]` in a value class and create instances for that. However, I'm not sure if people will like that. And it means that you can't treat `Kleisli[Future, ExecutionContext, ?]` as a monad.

I'm sorry if this isn't helpful at all - I'm just voicing a concern I've had about the scalaz approach to see if others have felt the same way or have ideas. I don't really have a great suggestion. I do wonder if something like this would better belong in a separate project or a module other than in `core`; that way it might be less concerning if it's not quite as neat and tidy.

**Comment by lvicentesanchez** [comment]
My main goal when I created this issue was to let people raise concerns now and not when I opened a PR :)

I don't really like the scalaz approach and I have also had problems with it, i.e. trying to use Kleisli[Future, ExecutionContext, ?] in for comprehensions without an implicit ExecutionContext in scope; but it's the most straight forward way to implement it.

It's not the first time somebody suggest me to implement a ExecutionContext => Future[A] monad adn use it instead of the plain Future monad so I think I'm going to give it a try.

**Comment by ceedubs** [comment]
@lvicentesanchez feel free to give it a try if you'll enjoy it, but it's quite possible that others will disagree with me or will have better ideas. I wouldn't want you to put effort into this that just gets discarded.

**Comment by lvicentesanchez** [comment]
I'm leaning towards providing an implementation similar to scalaz, a def instance, as an initial contribution. Once you are using scala Futures, implicit ExecutionContext are everywhere and it's really hard to runaway from them. I agree that this probably belongs to a "cats-contrib" instead of the core, as it used to be in scalaz until they move to the scalaz repository but I would like to hear the opinion from others.

In any case, I want also to explore the ExecutionContext => Future[A] route and see how far I could get... even if it's a dead end it could be useful for my own projects :)
